// Generates sitemap.xml from the real page set + real git commit dates.
//
// Hand-maintaining this file meant it drifted: every URL claimed the same
// lastmod long after the pages diverged, and a new project could ship without
// ever entering the sitemap. Project URLs now come from data.jsx (the same
// source generate-pages.mjs builds the pages from), so the two can't disagree.
//
// Only <loc> and <lastmod> are emitted. Google ignores <changefreq> and
// <priority> outright, and a wrong lastmod is worse than none, so each date is
// the newest commit touching any file that actually renders that page.

import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { execSync } from 'child_process';

const ROOT = new URL('.', import.meta.url).pathname;
const SITE = 'https://mohammadzayed.com';

const source = await readFile(join(ROOT, 'data.jsx'), 'utf-8');
const window = {};
new Function('window', source)(window);
const PROJECTS = window.PROJECTS;

if (!Array.isArray(PROJECTS) || PROJECTS.length === 0) {
  throw new Error('Could not load PROJECTS from data.jsx');
}

// Newest commit date across the whole repo. Used when a per-file lookup comes
// back empty, which happens on shallow CI clones where a file's last change is
// older than the fetch depth.
let headDate;
try {
  headDate = execSync('git log -1 --format=%cs', { cwd: ROOT }).toString().trim();
} catch {
  headDate = new Date().toISOString().slice(0, 10);
}

function lastCommitDate(file) {
  try {
    const out = execSync(`git log -1 --format=%cs -- "${file}"`, { cwd: ROOT })
      .toString()
      .trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : '';
  } catch {
    return '';
  }
}

// A page is only as fresh as the newest file that renders it. The homepage is
// React assembled from several files, so index.html's own date understates it.
function lastmodFor(sources) {
  const dates = sources.map(lastCommitDate).filter(Boolean);
  return dates.length ? dates.sort().at(-1) : headDate;
}

const SHARED = ['data.jsx', 'generate-pages.mjs'];

const PAGES = [
  { path: '/', sources: ['index.html', 'app.jsx', 'styles.css', 'data.jsx'] },
  { path: '/about', sources: ['about.html'] },
  { path: '/blog', sources: ['blog.html'] },
  ...PROJECTS.map((p) => ({ path: `/projects/${p.id}`, sources: SHARED })),
];

const escapeUrl = (s) =>
  String(s)
    .replaceAll('&', '&amp;')
    .replaceAll("'", '&apos;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');

const body = PAGES.map(
  ({ path, sources }) => `  <url>
    <loc>${escapeUrl(SITE + path)}</loc>
    <lastmod>${lastmodFor(sources)}</lastmod>
  </url>`,
).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by generate-sitemap.mjs during \`npm run build\`. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap-0.9">
${body}
</urlset>
`;

await writeFile(join(ROOT, 'sitemap.xml'), xml);

console.log(`✓ Wrote sitemap.xml (${PAGES.length} URLs)`);
